/** Build-only catalog. Never linked from public HTML. */
export const catalog = {
  company: {
    name: "YLK Infra Private Limited",
    short: "YLK Infra",
    tagline: "Build. Own. Grow.",
    city: "Bareilly",
    state: "Uttar Pradesh",
    country: "India",
    phone: "+91 94125 02030",
    phoneTel: "+919412502030",
    whatsapp: "919412502030",
    email: "hello@ylkinfra.in",
    address: "Civil Lines, Near Company Garden, Bareilly, Uttar Pradesh 243001",
    hours: "Mon–Sat, 9:30 AM – 7:00 PM",
    gst: "09XXXXX1234X1ZX",
    cin: "U70100UP2020PTCXXXXXX",
    mapQuery: "Civil+Lines+Bareilly",
    lat: 28.367,
    lng: 79.4304
  },
  auth: {
    user: "admin",
    passHash: "SHA256_PLACEHOLDER"
  },
  services: [
    { id: "plots", icon: "land", href: "plots.html" },
    { id: "flats", icon: "building", href: "flats.html" },
    { id: "villas", icon: "villa", href: "villas.html" },
    { id: "houses", icon: "home", href: "houses.html" },
    { id: "office", icon: "office", href: "office.html" },
    { id: "construction", icon: "crane", href: "construction.html" },
    { id: "renovation", icon: "renov", href: "renovation.html" },
    { id: "affordable", icon: "afford", href: "affordable.html" },
    { id: "ncr", icon: "ncr", href: "ncr.html" },
    { id: "invest", icon: "chart", href: "invest.html" }
  ],
  cities: [
    { id: "bareilly", name: "Bareilly", state: "UP", lat: 28.367, lng: 79.4304, note: "Head office & primary developments" },
    { id: "lucknow", name: "Lucknow", state: "UP", lat: 26.8467, lng: 80.9462, note: "Capital region homes & plots" },
    { id: "noida", name: "Noida", state: "NCR", lat: 28.5355, lng: 77.391, note: "Flats, offices, investment plots" },
    { id: "greater-noida", name: "Greater Noida", state: "NCR", lat: 28.4744, lng: 77.504, note: "Yamuna Expressway corridor" },
    { id: "ghaziabad", name: "Ghaziabad", state: "NCR", lat: 28.6692, lng: 77.4538, note: "Houses, offices, affordable" },
    { id: "gurugram", name: "Gurugram", state: "NCR", lat: 28.4595, lng: 77.0266, note: "Offices & luxury homes search" },
    { id: "faridabad", name: "Faridabad", state: "NCR", lat: 28.4089, lng: 77.3178, note: "Farmhouses & plotted land" },
    { id: "delhi", name: "New Delhi", state: "NCR", lat: 28.6139, lng: 77.209, note: "Office floors & resale homes" },
    { id: "jewar", name: "Jewar", state: "NCR", lat: 28.122, lng: 77.557, note: "Airport corridor land" },
    { id: "ayodhya", name: "Ayodhya", state: "UP", lat: 26.7922, lng: 82.1998, note: "Affordable & plotted" },
    { id: "meerut", name: "Meerut", state: "UP", lat: 28.9845, lng: 77.7064, note: "Affordable housing assist" },
    { id: "agra", name: "Agra", state: "UP", lat: 27.1767, lng: 78.0081, note: "PMAY-linked inventory" }
  ],
  testimonials: [
    {
      id: "t1",
      name: "Rohit Agarwal",
      role: "Plot owner, Bareilly",
      quote: "YLK walked us through NA conversion, 7/12 and registry like a family office — not a broker. The Greenfield plot is already worth more than we paid.",
      quoteHi: "YLK ने NA, 7/12 और रजिस्ट्री सब परिवार की तरह समझाया। ग्रीनफील्ड प्लॉट की कीमत पहले से बढ़ चुकी है।"
    },
    {
      id: "t2",
      name: "Neha & Arjun Malhotra",
      role: "3 BHK, Noida",
      quote: "From site visit to bank file, one WhatsApp thread. Honest about what was sold out. We booked the next available stack the same evening.",
      quoteHi: "साइट विजिट से बैंक फाइल तक एक व्हाट्सएप थ्रेड। जो बिक चुका था वो साफ बताया। उसी शाम अगला स्टैक बुक किया।"
    },
    {
      id: "t3",
      name: "Sanjay Verma",
      role: "Office floor, Indirapuram",
      quote: "Needed a ready office near the Metro. YLK showed three options with rent comps and we closed in 11 days.",
      quoteHi: "मेट्रो के पास रेडी ऑफिस चाहिए था। तीन विकल्प किराया तुलना के साथ दिखाए, 11 दिन में बंद हो गया।"
    },
    {
      id: "t4",
      name: "Farha Khan",
      role: "Renovation, Civil Lines",
      quote: "They rebuilt our 30-year house without us leaving Bareilly's chaos. Timeline stuck. Finishes better than the moodboards.",
      quoteHi: "30 साल पुराना घर बरेली में रहकर ही बनवाया। टाइमलाइन बनी रही। फिनिश मूडबोर्ड से बेहतर।"
    }
  ],
  faqs: [
    {
      q: "What does YLK Infra actually do?",
      qHi: "YLK Infra वास्तव में क्या करता है?",
      a: "We are a Bareilly-based builder, contractor and seller. We develop and sell plots, flats, villas and houses; take up new construction and renovation; and help you buy land, plots or office space anywhere in Delhi NCR and key UP cities.",
      aHi: "हम बरेली स्थित बिल्डर, ठेकेदार और विक्रेता हैं। प्लॉट, फ्लैट, विला, मकान विकसित व बेचते हैं; नई कंस्ट्रक्शन और रेनोवेशन करते हैं; दिल्ली एनसीआर व प्रमुख यूपी शहरों में ज़मीन, प्लॉट या ऑफिस खरीदने में मदद करते हैं।"
    },
    {
      q: "How do I book a unit?",
      qHi: "यूनिट कैसे बुक करूँ?",
      a: "Open any listing, tap Book / Enquire, share your name, WhatsApp number and email. The request goes straight to +91 94125 02030 on WhatsApp and is stored for our admin team.",
      aHi: "लिस्टिंग खोलें, बुक / पूछताछ दबाएँ, नाम, व्हाट्सएप और ईमेल भेजें। अनुरोध +91 94125 02030 पर व्हाट्सएप जाता है और एडमिन को दिखता है।"
    },
    {
      q: "Is inventory updated live?",
      qHi: "इन्वेंटरी लाइव अपडेट होती है?",
      a: "Yes. Our admin marks units Available, Booked or Sold Out. Sold and booked stock stays visible with a clear badge so you never chase a dead listing.",
      aHi: "हाँ। एडमिन उपलब्ध, बुक या सोल्ड आउट मार्क करता है। बिकी/बुकी स्टॉक बैज के साथ दिखती है।"
    },
    {
      q: "Do you help with affordable housing?",
      qHi: "क्या आप अफोर्डेबल हाउसिंग में मदद करते हैं?",
      a: "We assist families with PMAY-linked and state affordable projects in Bareilly, Lucknow, Kanpur, Agra, Meerut, Ghaziabad, Ayodhya and more — documentation, bank, and allotment follow-up.",
      aHi: "बरेली, लखनऊ, कानपुर, आगरा, मेरठ, गाजियाबाद, अयोध्या आदि में PMAY व राज्य अफोर्डेबल प्रोजेक्ट्स में दस्तावेज़, बैंक और आवंटन फॉलो-अप करते हैं।"
    },
    {
      q: "Can you find property anywhere in Delhi NCR?",
      qHi: "दिल्ली एनसीआर में कहीं भी प्रॉपर्टी मिल सकती है?",
      a: "Yes. Plots, builder floors, offices, warehouses and land across Noida, Greater Noida, Ghaziabad, Faridabad, Gurugram, Delhi and the Jewar airport belt. We charge a transparent advisory fee only after you shortlist.",
      aHi: "हाँ। नोएडा, ग्रेटर नोएडा, गाजियाबाद, फरीदाबाद, गुरुग्राम, दिल्ली और जेवर एयरपोर्ट बेल्ट में प्लॉट, बिल्डर फ्लोर, ऑफिस, गोदाम और ज़मीन। शॉर्टलिस्ट के बाद ही पारदर्शी फीस।"
    },
    {
      q: "Why is land a safer long-term investment?",
      qHi: "लंबी अवधि में ज़मीन सुरक्षित निवेश क्यों है?",
      a: "Land is finite, income-producing or developable, and historically hedges inflation in growth corridors. We still insist on title, NA status, access and flood/encumbrance checks — land is only safe when the paper is clean.",
      aHi: "ज़मीन सीमित है, आय या विकास दे सकती है, और ग्रोथ कॉरिडोर में महंगाई से बचाव रही है। टाइटल, NA, पहुंच और बाधा जांच ज़रूरी है — कागज़ साफ हों तभी ज़मीन सुरक्षित है।"
    }
  ],
  inventory: [
    {
      id: "ylk-greenfield-plots",
      slug: "greenfield-na-plots-bareilly",
      type: "plot",
      title: "Greenfield NA Plots",
      titleHi: "ग्रीनफील्ड NA प्लॉट्स",
      kicker: "Bareilly · Gated township",
      location: "Pilibhit Bypass, Bareilly",
      city: "Bareilly",
      state: "Uttar Pradesh",
      status: "available",
      price: 2490000,
      priceMax: 6200000,
      priceLabel: "₹24.9 Lakh*",
      area: "1,200–2,400 sq.ft",
      beds: null,
      baths: null,
      facing: "East / North",
      rera: "UPRERAPRJ140891",
      year: 2026,
      featured: true,
      lat: 28.401,
      lng: 79.462,
      highlights: ["Individual 7/12", "Internal 40 ft roads", "Club + parks", "Power & water"],
      highlightsHi: ["अलग 7/12", "40 फुट सड़कें", "क्लब व पार्क", "बिजली-पानी"],
      amenities: ["Gated security", "Clubhouse", "Walking trails", "Kids play", "Rainwater recharge", "Street lighting"],
      description: "A low-density NA plotted estate on Pilibhit Bypass — wide roads, parks and a clubhouse, with clean title and individual 7/12 extracts. Ideal for self-use bungalows or a 5–7 year hold in Bareilly's expanding east corridor.",
      descriptionHi: "पीलीभीत बाईपास पर कम घनत्व वाला NA प्लॉटेड एस्टेट — चौड़ी सड़कें, पार्क, क्लबहाउस, साफ टाइटल और अलग 7/12। खुद के बंगले या 5–7 साल होल्ड के लिए।",
      images: ["hero-plots.png", "plot-gated.png", "amenity-park.png", "amenity-club.png", "map-masterplan.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Project brochure", kind: "brochure" },
        { name: "Layout / master plan", kind: "map" },
        { name: "Sample 7/12 note", kind: "doc" },
        { name: "Payment schedule", kind: "doc" }
      ]
    },
    {
      id: "ylk-yamuna-plots",
      slug: "yamuna-expressway-plot-park",
      type: "plot",
      title: "Yamuna Expressway Plot Park",
      titleHi: "यमुना एक्सप्रेसवे प्लॉट पार्क",
      kicker: "Greater Noida · Investment plots",
      location: "Yamuna Expressway, Greater Noida",
      city: "Greater Noida",
      state: "Uttar Pradesh",
      status: "available",
      price: 4500000,
      priceMax: 12500000,
      priceLabel: "₹45 Lakh*",
      area: "100–300 sq.yd",
      facing: "Multiple",
      rera: "UPRERAPRJ209331",
      year: 2026,
      featured: true,
      lat: 28.39,
      lng: 77.58,
      highlights: ["Expressway frontage belt", "JEWAR 25–40 min", "Gated community", "Bank loans"],
      highlightsHi: ["एक्सप्रेसवे बेल्ट", "जेवर 25–40 मिनट", "गेटेड", "बैंक लोन"],
      amenities: ["Boundary wall", "Wide internal roads", "Park", "Security", "Electric poles"],
      description: "Plotted inventory along the Yamuna Expressway growth spine — sized for weekend homes or a patient land bank ahead of Jewar Airport and industrial demand.",
      descriptionHi: "यमुना एक्सप्रेसवे ग्रोथ स्पाइन पर प्लॉट्स — वीकेंड होम या जेवर एयरपोर्ट व उद्योग मांग से पहले लैंड बैंक।",
      images: ["land-invest.png", "plot-gated.png", "ncr-skyline.png", "map-masterplan.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Project brochure", kind: "brochure" },
        { name: "Location map", kind: "map" },
        { name: "Title summary", kind: "doc" }
      ]
    },
    {
      id: "ylk-jewar-land",
      slug: "jewar-airport-corridor-land",
      type: "land",
      title: "Jewar Airport Corridor Land",
      titleHi: "जेवर एयरपोर्ट कॉरिडोर लैंड",
      kicker: "NCR · Institutional / farm parcels",
      location: "Jewar–Tappal belt, NCR",
      city: "Jewar",
      state: "Uttar Pradesh",
      status: "available",
      price: 8500000,
      priceMax: 42000000,
      priceLabel: "₹85 Lakh*",
      area: "0.5–5 acres",
      facing: "Road abutting",
      rera: "Advisory inventory",
      year: 2026,
      featured: true,
      lat: 28.122,
      lng: 77.557,
      highlights: ["Airport influence zone", "Due diligence pack", "Khasra options", "Farm / warehouse use"],
      highlightsHi: ["एयरपोर्ट ज़ोन", "ड्यू डिलिजेंस पैक", "खसरा विकल्प", "फार्म / गोदाम"],
      amenities: ["Site visit from Noida", "Advocate vetting", "Mutation support"],
      description: "Curated agricultural and potential CLU parcels in the Jewar influence zone. We do not sell blind acres — every parcel ships with khasra, jamabandi snapshot and an access note.",
      descriptionHi: "जेवर प्रभाव क्षेत्र में चुनी हुई कृषि व संभावित CLU पार्सल। हर पार्सल के साथ खसरा, जमाबंदी और पहुंच नोट।",
      images: ["land-invest.png", "ncr-skyline.png", "farmhouse-estate.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Investment thesis", kind: "brochure" },
        { name: "Corridor map", kind: "map" },
        { name: "Due-diligence checklist", kind: "doc" }
      ]
    },
    {
      id: "ylk-civil-flats",
      slug: "civil-lines-residences-bareilly",
      type: "flat",
      title: "Civil Lines Residences",
      titleHi: "सिविल लाइन्स रेजिडेंसेस",
      kicker: "Bareilly · 2 & 3 BHK",
      location: "Civil Lines, Bareilly",
      city: "Bareilly",
      state: "Uttar Pradesh",
      status: "available",
      price: 3850000,
      priceMax: 7200000,
      priceLabel: "₹38.5 Lakh*",
      area: "980–1,650 sq.ft",
      beds: 3,
      baths: 2,
      facing: "Park / East",
      rera: "UPRERAPRJ156002",
      year: 2027,
      featured: true,
      lat: 28.364,
      lng: 79.415,
      highlights: ["Lift + power backup", "Covered parking", "City-centre", "Vaastu stacks"],
      highlightsHi: ["लिफ्ट व बैकअप", "कवर्ड पार्किंग", "सिटी सेंटर", "वास्तु स्टैक"],
      amenities: ["Gym", "Kids play", "24x7 security", "Intercom", "Rainwater pit"],
      description: "A boutique mid-rise in Civil Lines for families who want city convenience without leaving Bareilly's most trusted address. 2 & 3 BHK with park-facing stacks still available.",
      descriptionHi: "सिविल लाइन्स में बुटीक मिड-राइज़ — शहर की सुविधा, विश्वसनीय पता। पार्क-फेसिंग 2 व 3 BHK उपलब्ध।",
      images: ["hero-flats.png", "interior-suite.png", "amenity-club.png", "bareilly-city.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Brochure & typical floor", kind: "brochure" },
        { name: "Location map", kind: "map" },
        { name: "Spec sheet", kind: "doc" }
      ]
    },
    {
      id: "ylk-noida-150",
      slug: "noida-sector-150-3bhk",
      type: "flat",
      title: "Sector 150 · 3 BHK Skyline",
      titleHi: "सेक्टर 150 · 3 BHK स्काईलाइन",
      kicker: "Noida · Sold out",
      location: "Sector 150, Noida",
      city: "Noida",
      state: "Uttar Pradesh",
      status: "sold",
      price: 16800000,
      priceLabel: "₹1.68 Cr*",
      area: "1,850 sq.ft",
      beds: 3,
      baths: 3,
      facing: "Golf / Expressway",
      rera: "UPRERAPRJ98821",
      year: 2025,
      featured: false,
      lat: 28.42,
      lng: 77.48,
      highlights: ["Sold out", "Waitlist open", "Club ready"],
      highlightsHi: ["सोल्ड आउट", "वेटलिस्ट", "क्लब रेडी"],
      amenities: ["Club", "Pool", "Jogging track", "Retail"],
      description: "This stack is sold out. Join the waitlist — we still advise resale and next-phase inventory in Sector 150 / 168.",
      descriptionHi: "यह स्टैक बिक चुका है। वेटलिस्ट जॉइन करें — सेक्टर 150/168 में रीसेल व अगली फेज़ की सलाह देते हैं।",
      images: ["hero-flats.png", "penthouse-terrace.png", "amenity-club.png", "ncr-skyline.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Waitlist note", kind: "brochure" },
        { name: "Location map", kind: "map" }
      ]
    },
    {
      id: "ylk-gnoida-west",
      slug: "greater-noida-west-4bhk",
      type: "flat",
      title: "Greater Noida West 4 BHK",
      titleHi: "ग्रेटर नोएडा वेस्ट 4 BHK",
      kicker: "NCR · Token booked",
      location: "Greater Noida West",
      city: "Greater Noida",
      state: "Uttar Pradesh",
      status: "booked",
      price: 12900000,
      priceLabel: "₹1.29 Cr*",
      area: "2,150 sq.ft",
      beds: 4,
      baths: 4,
      facing: "Park",
      rera: "UPRERAPRJ112440",
      year: 2026,
      featured: false,
      lat: 28.62,
      lng: 77.44,
      highlights: ["Token received", "Similar units on request", "Metro catchment"],
      highlightsHi: ["टोकन प्राप्त", "समान यूनिट पूछें", "मेट्रो कैचमेंट"],
      amenities: ["Club", "Pool", "Sports courts", "High street retail"],
      description: "This particular 4 BHK is under token. Ask us for mirroring stacks or a comparable tower in GN West.",
      descriptionHi: "यह 4 BHK टोकन के अंतर्गत है। मिरर स्टैक या GN वेस्ट में तुलनीय टॉवर पूछें।",
      images: ["hero-flats.png", "amenity-club.png", "interior-suite.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Tower brochure", kind: "brochure" },
        { name: "Site map", kind: "map" }
      ]
    },
    {
      id: "ylk-pilibhit-villas",
      slug: "pilibhit-road-garden-villas",
      type: "villa",
      title: "Pilibhit Road Garden Villas",
      titleHi: "पीलीभीत रोड गार्डन विला",
      kicker: "Bareilly · 4 BHK villas",
      location: "Pilibhit Road, Bareilly",
      city: "Bareilly",
      state: "Uttar Pradesh",
      status: "available",
      price: 18500000,
      priceMax: 26500000,
      priceLabel: "₹1.85 Cr*",
      area: "2,800–3,600 sq.ft",
      beds: 4,
      baths: 4,
      facing: "Garden",
      rera: "UPRERAPRJ167210",
      year: 2027,
      featured: true,
      lat: 28.39,
      lng: 79.47,
      highlights: ["Private lawn", "Servant room", "Modular kitchen", "EV charging"],
      highlightsHi: ["निजी लॉन", "नौकर रूम", "मॉड्यूलर किचन", "EV चार्ज"],
      amenities: ["Gated street", "Club", "Pool", "Landscaped boulevard"],
      description: "Independent garden villas with double-height living and a quiet internal street — built for joint families who still want Bareilly five minutes away.",
      descriptionHi: "डबल-हाइट लिविंग वाले स्वतंत्र गार्डन विला — संयुक्त परिवारों के लिए, बरेली पाँच मिनट।",
      images: ["villa-prestige.png", "interior-suite.png", "amenity-club.png", "hero-estate.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Villa brochure", kind: "brochure" },
        { name: "Floor plans", kind: "doc" },
        { name: "Layout map", kind: "map" }
      ]
    },
    {
      id: "ylk-farmhouse-ncr",
      slug: "aravali-fringe-farmhouse",
      type: "villa",
      title: "Aravali Fringe Farmhouse Plots",
      titleHi: "अरावली फ्रिंज फार्महाउस प्लॉट्स",
      kicker: "Faridabad · Weekend estate",
      location: "Faridabad–Sohna fringe, NCR",
      city: "Faridabad",
      state: "Haryana",
      status: "available",
      price: 11000000,
      priceMax: 33000000,
      priceLabel: "₹1.10 Cr*",
      area: "1,000–2,500 sq.yd",
      beds: 3,
      baths: 3,
      facing: "Open green",
      rera: "HRERA advisory",
      year: 2026,
      featured: true,
      lat: 28.35,
      lng: 77.28,
      highlights: ["Weekend home", "Orchard possible", "Gated cluster", "90 min Delhi"],
      highlightsHi: ["वीकेंड होम", "बाग संभव", "गेटेड", "दिल्ली 90 मिनट"],
      amenities: ["Club", "Pool", "Trails", "Security"],
      description: "Low-density farmhouse plots on the Aravali fringe for families who want silence without losing the NCR. Optional construction by YLK.",
      descriptionHi: "अरावली किनारे कम घनत्व फार्महाउस प्लॉट। YLK से वैकल्पिक कंस्ट्रक्शन।",
      images: ["farmhouse-estate.png", "land-invest.png", "amenity-club.png", "hero-estate.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Estate brochure", kind: "brochure" },
        { name: "Access map", kind: "map" },
        { name: "CLU note", kind: "doc" }
      ]
    },
    {
      id: "ylk-civil-house",
      slug: "civil-lines-independent-house",
      type: "house",
      title: "Civil Lines Independent House",
      titleHi: "सिविल लाइन्स स्वतंत्र मकान",
      kicker: "Bareilly · Ready possession",
      location: "Civil Lines, Bareilly",
      city: "Bareilly",
      state: "Uttar Pradesh",
      status: "available",
      price: 9800000,
      priceLabel: "₹98 Lakh*",
      area: "2,100 sq.ft built / 180 sq.yd plot",
      beds: 4,
      baths: 3,
      facing: "North-East",
      rera: "Resale · freehold",
      year: 2018,
      featured: false,
      lat: 28.366,
      lng: 79.42,
      highlights: ["Freehold", "Renovated 2024", "Car porch", "Terrace garden"],
      highlightsHi: ["फ्रीहोल्ड", "2024 रेनोवेशन", "कार पोर्च", "टेरेस गार्डन"],
      amenities: ["Wardrobes", "Modular kitchen", "Solar option"],
      description: "A lived-in Civil Lines house, structurally sound and refreshed in 2024. Registry-ready with municipal water and a quiet lane.",
      descriptionHi: "सिविल लाइन्स का मकान, 2024 में ताज़ा। रजिस्ट्री रेडी, नगर जल, शांत गली।",
      images: ["house-civil.png", "renovate-living.png", "interior-suite.png", "bareilly-city.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "House dossier", kind: "brochure" },
        { name: "Location map", kind: "map" },
        { name: "Title checklist", kind: "doc" }
      ]
    },
    {
      id: "ylk-sitapur-house",
      slug: "sitapur-bypass-house-lucknow",
      type: "house",
      title: "Sitapur Bypass House",
      titleHi: "सीतापुर बाईपास मकान",
      kicker: "Lucknow · Sold",
      location: "Sitapur Bypass, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
      status: "sold",
      price: 12500000,
      priceLabel: "₹1.25 Cr*",
      area: "2,400 sq.ft",
      beds: 4,
      baths: 4,
      facing: "East",
      rera: "Resale",
      year: 2020,
      featured: false,
      lat: 26.9,
      lng: 80.97,
      highlights: ["Sold", "Similar homes on request"],
      highlightsHi: ["बिक चुका", "समान घर पूछें"],
      amenities: ["Garden", "Parking", "Wardrobes"],
      description: "This home has been sold. We keep a private list of similar independent houses on Sitapur Bypass and Gomti Nagar Extension.",
      descriptionHi: "यह घर बिक चुका है। सीतापुर बाईपास व गोमती नगर एक्सटेंशन में समान घरों की निजी सूची है।",
      images: ["house-civil.png", "renovate-living.png"],
      mapImage: "map-masterplan.png",
      documents: [{ name: "Sold notice", kind: "doc" }]
    },
    {
      id: "ylk-cp-office",
      slug: "connaught-place-office-suite",
      type: "office",
      title: "Connaught Place Office Suite",
      titleHi: "कनॉट प्लेस ऑफिस सुइट",
      kicker: "New Delhi · Plug & play",
      location: "Outer Circle, Connaught Place, New Delhi",
      city: "New Delhi",
      state: "Delhi",
      status: "available",
      price: 28500000,
      priceLabel: "₹2.85 Cr*",
      area: "1,120 sq.ft",
      beds: null,
      baths: 2,
      facing: "Circle",
      rera: "Commercial · lease or sale",
      year: 2012,
      featured: true,
      lat: 28.6304,
      lng: 77.2177,
      highlights: ["Metro 3 min", "Fitted cabins", "Central AC", "Lease option"],
      highlightsHi: ["मेट्रो 3 मिनट", "फिटेड केबिन", "सेंट्रल AC", "लीज विकल्प"],
      amenities: ["Reception", "Pantry", "Washrooms", "Power backup"],
      description: "A fitted CP suite for firms that need a Delhi address without a 12-month interior wait. Sale or 5-year lease.",
      descriptionHi: "दिल्ली पते के लिए फिटेड CP सुइट — बिक्री या 5 वर्ष लीज।",
      images: ["office-suite.png", "office-exterior.png", "ncr-skyline.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Office brief", kind: "brochure" },
        { name: "Floor plate", kind: "map" },
        { name: "Lease term sheet", kind: "doc" }
      ]
    },
    {
      id: "ylk-indirapuram-office",
      slug: "indirapuram-office-floor",
      type: "office",
      title: "Indirapuram Office Floor",
      titleHi: "इंदिरापुरम ऑफिस फ्लोर",
      kicker: "Ghaziabad · Half floor",
      location: "Indirapuram, Ghaziabad",
      city: "Ghaziabad",
      state: "Uttar Pradesh",
      status: "available",
      price: 14200000,
      priceLabel: "₹1.42 Cr*",
      area: "2,400 sq.ft",
      facing: "Arterial road",
      rera: "Commercial",
      year: 2016,
      featured: false,
      lat: 28.64,
      lng: 77.37,
      highlights: ["Open floor", "NCR talent pool", "Parking 6 ECS", "IT/ITES ready"],
      highlightsHi: ["ओपन फ्लोर", "एनसीआर टैलेंट", "6 ECS पार्किंग", "IT रेडी"],
      amenities: ["Lift", "Backup", "Cafeteria nearby"],
      description: "Half-floor plate for a 25–40 seat team. Strong for back-office, clinic chain HQ or boutique IT.",
      descriptionHi: "25–40 सीट टीम के लिए हाफ फ्लोर — बैक ऑफिस, क्लिनिक HQ या बुटीक IT।",
      images: ["office-exterior.png", "office-suite.png", "ncr-skyline.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Floor brochure", kind: "brochure" },
        { name: "Access map", kind: "map" }
      ]
    },
    {
      id: "ylk-ayodhya-afford",
      slug: "ayodhya-affordable-homes",
      type: "affordable",
      title: "Ayodhya Affordable Homes",
      titleHi: "अयोध्या अफोर्डेबल होम्स",
      kicker: "PMAY-linked · 1 & 2 BHK",
      location: "Faizabad Road belt, Ayodhya",
      city: "Ayodhya",
      state: "Uttar Pradesh",
      status: "available",
      price: 1850000,
      priceMax: 3200000,
      priceLabel: "₹18.5 Lakh*",
      area: "420–680 sq.ft",
      beds: 2,
      baths: 1,
      facing: "Open",
      rera: "UPRERAPRJ174400",
      year: 2027,
      featured: true,
      lat: 26.792,
      lng: 82.2,
      highlights: ["PMAY assist", "Bank panel", "Gated", "Temple-city demand"],
      highlightsHi: ["PMAY मदद", "बैंक पैनल", "गेटेड", "मंदिर नगर मांग"],
      amenities: ["Park", "Security", "Community hall"],
      description: "Compact 1 & 2 BHK inventory with PMAY documentation support. Built for end-users and small investors tracking Ayodhya's long tourism cycle.",
      descriptionHi: "PMAY दस्तावेज़ मदद के साथ 1 व 2 BHK। एंड-यूज़र व छोटे निवेशक के लिए।",
      images: ["affordable-homes.png", "amenity-park.png", "hero-flats.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Scheme brochure", kind: "brochure" },
        { name: "PMAY checklist", kind: "doc" },
        { name: "Location map", kind: "map" }
      ]
    },
    {
      id: "ylk-lucknow-afford",
      slug: "gomti-extension-affordable",
      type: "affordable",
      title: "Gomti Extension Affordable",
      titleHi: "गोमती एक्सटेंशन अफोर्डेबल",
      kicker: "Lucknow · EWS / LIG / MIG",
      location: "Gomti Nagar Extension, Lucknow",
      city: "Lucknow",
      state: "Uttar Pradesh",
      status: "available",
      price: 2100000,
      priceMax: 4100000,
      priceLabel: "₹21 Lakh*",
      area: "450–750 sq.ft",
      beds: 2,
      baths: 2,
      rera: "UPRERAPRJ188120",
      year: 2026,
      featured: false,
      lat: 26.86,
      lng: 81.02,
      highlights: ["Income-slab units", "Metro plan catchment", "YLK file support"],
      highlightsHi: ["आय स्लैब यूनिट", "मेट्रो कैचमेंट", "YLK फाइल सपोर्ट"],
      amenities: ["Park", "Shop line", "Security"],
      description: "EWS, LIG and compact MIG apartments. We help with income proofs, Aadhaar-bank seeding and lottery/allotment paperwork where the scheme requires it.",
      descriptionHi: "EWS, LIG व कॉम्पैक्ट MIG। आय प्रमाण, आधार-बैंक और आवंटन कागज़ी मदद।",
      images: ["affordable-homes.png", "amenity-park.png", "house-civil.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Typology brochure", kind: "brochure" },
        { name: "Eligibility note", kind: "doc" },
        { name: "Map", kind: "map" }
      ]
    },
    {
      id: "ylk-bareilly-penthouse",
      slug: "bareilly-city-penthouse",
      type: "flat",
      title: "Bareilly City Penthouse",
      titleHi: "बरेली सिटी पेंटहाउस",
      kicker: "Bareilly · Duplex terrace",
      location: "Rampur Garden, Bareilly",
      city: "Bareilly",
      state: "Uttar Pradesh",
      status: "available",
      price: 15500000,
      priceLabel: "₹1.55 Cr*",
      area: "3,200 sq.ft + terrace",
      beds: 4,
      baths: 4,
      facing: "City / West",
      rera: "UPRERAPRJ161004",
      year: 2026,
      featured: true,
      lat: 28.3675,
      lng: 79.43,
      highlights: ["Private terrace", "Private lift lobby", "Smart home", "Panoramic dusk"],
      highlightsHi: ["निजी टेरेस", "लिफ्ट लॉबी", "स्मार्ट होम", "सिटी व्यू"],
      amenities: ["Pool access", "Gym", "Concierge"],
      description: "A duplex penthouse over Rampur Garden for buyers who want Bareilly's skyline and a terrace they actually use.",
      descriptionHi: "रामपुर गार्डन के ऊपर डुप्लेक्स पेंटहाउस — बरेली स्काईलाइन और इस्तेमाल लायक टेरेस।",
      images: ["penthouse-terrace.png", "hero-flats.png", "interior-suite.png", "amenity-club.png"],
      mapImage: "map-masterplan.png",
      documents: [
        { name: "Penthouse brochure", kind: "brochure" },
        { name: "Terrace plan", kind: "map" }
      ]
    },
    {
      id: "ylk-rajnagar-house",
      slug: "raj-nagar-extension-house",
      type: "house",
      title: "Raj Nagar Extension House",
      titleHi: "राज नगर एक्सटेंशन मकान",
      kicker: "Ghaziabad · Booked",
      location: "Raj Nagar Extension, Ghaziabad",
      city: "Ghaziabad",
      state: "Uttar Pradesh",
      status: "booked",
      price: 8900000,
      priceLabel: "₹89 Lakh*",
      area: "1,850 sq.ft",
      beds: 3,
      baths: 3,
      facing: "Park",
      rera: "Resale",
      year: 2019,
      featured: false,
      lat: 28.69,
      lng: 77.4,
      highlights: ["Token booked", "Similar builder floors"],
      highlightsHi: ["टोकन बुक", "समान बिल्डर फ्लोर"],
      amenities: ["Park facing", "Car park"],
      description: "Currently under token. We can still show neighbouring builder floors in Raj Nagar Extension this week.",
      descriptionHi: "टोकन के अंतर्गत। राज नगर एक्सटेंशन में पड़ोसी बिल्डर फ्लोर इसी सप्ताह दिखा सकते हैं।",
      images: ["house-civil.png", "amenity-park.png"],
      mapImage: "map-masterplan.png",
      documents: [{ name: "Floor note", kind: "doc" }]
    }
  ]
};
