/** Each theme gets its own layout id — no sharing between themes */
module.exports = {
  kadu: {
    name: 'Kadu',
    layout: 'kadu',
    font: 'Jost',
    fontUrl: 'Jost:wght@400;500;600;700;800',
    primary: '#7c3aed',
    secondary: '#f59e0b',
    accent: '#a78bfa',
    bg: '#fafafa',
    text: '#1e1b4b',
    muted: '#64748b',
    dark: false,
    demo: 'themexriver.com/wp/kadu',
    tagline: 'Online Platform For Education',
    heroStyle: 'slider-purple',
    cardStyle: 'elevated'
  },
  bornomala: {
    name: 'Bornomala',
    layout: 'bornomala',
    font: 'Nunito',
    fontUrl: 'Nunito:wght@400;600;700;800;900',
    primary: '#ff6b9d',
    secondary: '#4ecdc4',
    accent: '#ffe66d',
    bg: '#fff0f5',
    text: '#2d3436',
    muted: '#636e72',
    dark: false,
    demo: 'wpdemothemes.com/bornomala',
    tagline: 'Kindergarten & Primary School',
    heroStyle: 'bubbles-pink',
    cardStyle: 'rounded-bubble'
  },
  eduvision: {
    name: 'EduVision',
    layout: 'eduvision',
    font: 'Roboto',
    fontUrl: 'Roboto:wght@400;500;700;900',
    primary: '#0066cc',
    secondary: '#00a651',
    accent: '#3399ff',
    bg: '#eef4fc',
    text: '#1a1a2e',
    muted: '#5a6a7a',
    dark: false,
    demo: 'shtheme.com/demosd/eduvisionwp',
    tagline: 'Multipurpose Education Theme',
    heroStyle: 'split-blue',
    cardStyle: 'bordered'
  },
  ischool: {
    name: 'iSchool',
    layout: 'ischool',
    font: 'Inter',
    fontUrl: 'Inter:wght@400;500;600;700;800',
    primary: '#00a878',
    secondary: '#ff6b35',
    accent: '#00c896',
    bg: '#f4fbf8',
    text: '#1a2332',
    muted: '#6b7c93',
    dark: false,
    demo: 'ischool.themerex.net',
    tagline: 'University & Online Courses',
    heroStyle: 'video-green',
    cardStyle: 'pricing'
  },
  edusion: {
    name: 'Edusion',
    layout: 'edusion',
    font: 'Montserrat',
    fontUrl: 'Montserrat:wght@400;500;600;700;800',
    primary: '#ff6b35',
    secondary: '#4dabf7',
    accent: '#ff8c5a',
    bg: '#0a0f1e',
    text: '#eef2ff',
    muted: '#94a3b8',
    dark: true,
    demo: 'wpdemothemes.com/edusion',
    tagline: 'Modern Learning Platform',
    heroStyle: 'dark-coral',
    cardStyle: 'glass'
  },
  eduall: {
    name: 'EduAll',
    layout: 'eduall',
    font: 'Inter',
    fontUrl: 'Inter:wght@400;500;600;700;800',
    primary: '#6366f1',
    secondary: '#f59e0b',
    accent: '#818cf8',
    bg: '#0b0b1a',
    text: '#e2e8f0',
    muted: '#94a3b8',
    dark: true,
    demo: 'html.themewin.com/edurock/index-dark.html',
    tagline: 'Cloud-based LMS Trusted by 1000+',
    heroStyle: 'edurock-dark',
    cardStyle: 'edurock'
  },
  kidso: {
    name: 'Kidso',
    layout: 'kidso',
    font: 'Quicksand',
    fontUrl: 'Quicksand:wght@400;500;600;700',
    primary: '#ffb800',
    secondary: '#ff6b6b',
    accent: '#4ecdc4',
    bg: '#fff8e7',
    text: '#3d3000',
    muted: '#8a7340',
    dark: false,
    demo: 'wpdemo.zcubethemes.com/kidso',
    tagline: 'Childcare & Early Learning',
    heroStyle: 'sunshine-yellow',
    cardStyle: 'playful-block'
  },
  eginary: {
    name: 'Eginary',
    layout: 'eginary',
    font: 'Open Sans',
    fontUrl: 'Open+Sans:wght@400;600;700;800',
    primary: '#0891b2',
    secondary: '#06b6d4',
    accent: '#22d3ee',
    bg: '#ecfeff',
    text: '#164e63',
    muted: '#0e7490',
    dark: false,
    demo: 'designingmedia.com/eginary',
    tagline: 'Smart Learning Solutions',
    heroStyle: 'teal-wave',
    cardStyle: 'left-accent'
  },
  wellearn: {
    name: 'WellLearn',
    layout: 'wellearn',
    font: 'Raleway',
    fontUrl: 'Raleway:wght@400;500;600;700;800',
    primary: '#7c3aed',
    secondary: '#ec4899',
    accent: '#a855f7',
    bg: '#fdf4ff',
    text: '#3b0764',
    muted: '#7e22ce',
    dark: false,
    demo: 'gaviaspreview.com/wp/wellearn/home-3',
    tagline: 'Education Hub & LMS',
    heroStyle: 'purple-gradient',
    cardStyle: 'gradient-border'
  },
  edrio: {
    name: 'Edrio',
    layout: 'edrio',
    font: 'Fredoka',
    fontUrl: 'Fredoka:wght@400;500;600;700',
    primary: '#ff6b6b',
    secondary: '#ffd93d',
    accent: '#6bcb77',
    bg: '#fff5eb',
    text: '#4a2800',
    muted: '#8a6040',
    dark: false,
    demo: 'themexriver.com/wp/edrio/home-3',
    tagline: 'Kindergarten Classic Theme',
    heroStyle: 'dashed-playful',
    cardStyle: 'star-card'
  },
  'los-ninos': {
    name: 'Los Niños',
    layout: 'los-ninos',
    font: 'Baloo 2',
    fontUrl: 'Baloo+2:wght@400;500;600;700;800',
    primary: '#27ae60',
    secondary: '#f39c12',
    accent: '#e74c3c',
    bg: '#edfff3',
    text: '#1a4d2e',
    muted: '#3d7a55',
    dark: false,
    demo: 'los-ninos.cmsmasters.studio/los-ninos',
    tagline: 'Playful Learning Center',
    heroStyle: 'nature-green',
    cardStyle: 'organic'
  },
  kidscholl: {
    name: 'Kidscholl',
    layout: 'kidscholl',
    font: 'Nunito',
    fontUrl: 'Nunito:wght@400;600;700;800;900',
    primary: '#3498db',
    secondary: '#f1c40f',
    accent: '#e74c3c',
    bg: '#e8f4fc',
    text: '#1a3a5c',
    muted: '#5a7a9a',
    dark: false,
    demo: 'kidschollwp.wowtheme7.com',
    tagline: 'Preschool & Kindergarten',
    heroStyle: 'wave-blue',
    cardStyle: 'wave-card'
  },
  ascen: {
    name: 'Ascen',
    layout: 'ascen',
    font: 'Poppins',
    fontUrl: 'Poppins:wght@400;500;600;700;800',
    primary: '#e17055',
    secondary: '#00b894',
    accent: '#fdcb6e',
    bg: '#fff5f0',
    text: '#4a2010',
    muted: '#8a5040',
    dark: false,
    demo: 'wpdemothemes.com/ascen',
    tagline: 'Childcare & Kids School',
    heroStyle: 'coral-soft',
    cardStyle: 'soft-pill'
  },
  cutie: {
    name: 'Cutie',
    layout: 'cutie',
    font: 'Comfortaa',
    fontUrl: 'Comfortaa:wght@400;500;600;700',
    primary: '#ff7675',
    secondary: '#74b9ff',
    accent: '#ffeaa7',
    bg: '#fff8f5',
    text: '#5c2020',
    muted: '#9a6060',
    dark: false,
    demo: 'wdtcutie.wpenginepowered.com',
    tagline: 'Creative Education Theme',
    heroStyle: 'cloud-pastel',
    cardStyle: 'cloud-card'
  },
  kiddoz: {
    name: 'Kiddoz',
    layout: 'kiddoz',
    font: 'Outfit',
    fontUrl: 'Outfit:wght@400;500;600;700;800',
    primary: '#00cec9',
    secondary: '#6c5ce7',
    accent: '#fdcb6e',
    bg: '#e8fffe',
    text: '#0a3a38',
    muted: '#3a7a78',
    dark: false,
    demo: 'kiddoz.axiomthemes.com',
    tagline: 'School & Kindergarten',
    heroStyle: 'geometric-cyan',
    cardStyle: 'diamond-card'
  }
};
